### ISSUE TITLE
Fonction Start

### ISSUE THREAD

**Issue by Capablanca4** [DevJo68/SimulationManifestation#2]
La fonction start plante l'affichage graphique à cause du Thread.Sleep que j'ai implémenté.
Il faudrait trouver une autre option qui ne bloque pas l'affichage. Sans doute avec des task mais je ne m'y connais pas assez en java pour pouvoir affirmer que c'est la meilleure option. 
Si l'un de vous à une idée il peur la proposer en dessous.

**Comment by vmpikaso** [comment]
Euh tu est sur quelle branche ??

**Comment by vmpikaso** [comment]
c'est bon je crois que j'ai trouvé une solution au problème

**Comment by Capablanca4** [comment]
je travaille sur ta branche temporairement pour faire quelques modifications rapidement.

**Comment by vmpikaso** [comment]
Pour le moment on peut lancer et stop l'affichage mais l'affichage ne change pas d'un pouce
